import React, { Component } from 'react'
import NewsItem from './NewsItem'

export class NewsComponent extends Component {
  constructor() {
    super();
    this.state = {

    }
  }
  articles = [
    {
      "source": {
        "id": "engadget",
        "name": "Engadget"
      },
      "author": "Jon Fingas",
      "title": "Trombone Champ's 'autotoot' makes the ridiculous music game more accessible",
      "description": "Trombone Champ is a blast to watch, but a beast to play even compared to some other rhythm games — you try nailing a slide during the \"William Tell Overture.\" Thankfully, developer Holy Wow Studios is putting the game within reach of more players. It's introd…",
      "url": "https://www.engadget.com/trombone-champs-autotoot-makes-the-ridiculous-music-game-more-accessible-192059126.html",
      "urlToImage": "https://s.yimg.com/uu/api/res/1.2/B6H6017ChfW5GVWaN.JfZA--~B/Zmk9ZmlsbDtoPTYzMDtweW9mZj0wO3c9MTIwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2023-03/53acba10-c4ef-11ed-9be7-61f84ae2fee9.cf.jpg",
      "publishedAt": "2023-03-17T19:20:59Z",
      "content": "Trombone Champ is a blast to watch, but a beast to play even compared to some other rhythm games you try nailing a slide during the \"William Tell Overture.\" Thankfully, developer Holy Wow Studios is … [+1646 chars]"
    },
    {
      "source": {
        "id": "wired",
        "name": "Wired"
      },
      "author": "Will Bedingfield",
      "title": "Musicians, Machines, and the AI-Powered Future of Sound",
      "description": "Fears that computers could replace composers are real. But some music-makers are finding ways to harness generative AI creatively.",
      "url": "https://www.wired.com/story/generative-ai-music/",
      "urlToImage": "https://media.wired.com/photos/64125850412651fa6ee1479c/191:100/w_1280,c_limit/AI-Powered-Future-of-Sound-Culture-1439768811.jpg",
      "publishedAt": "2023-03-16T11:00:00Z",
      "content": "Musicians have also reacted to the general unease generated by ChatGPT and Bings AI chatbot. Bogdan Raczynski, reading transcripts of the chatbots viral discussions with humans, says over email that … [+3082 chars]"
    },
    {
      "source": {
        "id": "engadget",
        "name": "Engadget"
      },
      "author": "Steve Dent",
      "title": "Apple Music bug on iOS is reportedly mixing up people's playlists",
      "description": "Apple Music users on iOS are highlighting a fairly serious bug that is causing other people's playlists and songs to appear in their libraries, according to multiple Redditors. On top of that, some users have complained that their own playlists have outright …",
      "url": "https://www.engadget.com/apple-music-bug-on-ios-is-reportedly-mixing-up-peoples-playlists-073003381.html",
      "urlToImage": "https://s.yimg.com/uu/api/res/1.2/nI1OvVbO7jgK9vgdLUC2zA--~B/Zmk9ZmlsbDtoPTYzMDtweW9mZj0wO3c9MTIwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2023-03/55f97d90-c93f-11ed-a3ff-26d7308c2770.cf.jpg",
      "publishedAt": "2023-03-23T10:30:03Z",
      "content": "Apple Music users on iOS are highlighting a fairly serious bug that is causing other people's playlists and songs to appear in their libraries, according to multiple Redditors. On top of that, some u… [+866 chars]"
    },
    {
      "source": {
        "id": "engadget",
        "name": "Engadget"
      },
      "author": "Igor Bonifacic",
      "title": "Aimi's app for listening to AI-generated beats arrives on Android and iOS",
      "description": "Following a beta that saw just 5,000 people get a chance to use the software, Aimi’s iOS and Android app is now available to all. The release brings the company’s generative music platform to mobile, where it was not available previously. Engadget’s James Tre…",
      "url": "https://www.engadget.com/aimis-app-for-listening-to-ai-generated-beats-arrives-on-android-and-ios-150035919.html",
      "urlToImage": "https://s.yimg.com/uu/api/res/1.2/EKHhsBrPKBf9F7RalnQcXg--~B/Zmk9ZmlsbDtoPTYzMDtweW9mZj0wO3c9MTIwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2023-03/0376da40-bc5b-11ed-9bde-3c0dad4a99a0.cf.jpg",
      "publishedAt": "2023-03-09T15:00:35Z",
      "content": "Following a beta that saw just 5,000 people get a chance to use the software, Aimis iOS and Android app is now available to all. The release brings the companys generative music platform to mobile, w… [+2061 chars]"
    },
    {
      "source": {
        "id": null,
        "name": "Gizmodo.com"
      },
      "author": "Mack DeGeurin",
      "title": "8 Music Videos That Show How Fast Deepfakes Are Evolving",
      "description": "The sudden explosion of OpenAI’s ChatGPT and other large language models has led to renewed attention on artificial intelligence that’s capable of mimicking speech, especially for well-known figures. It has left some spectators fearful of a rise in deepfake-f…",
      "url": "https://gizmodo.com/ai-deepfake-evolution-music-videos-kendrick-ye-eminem-1850209990",
      "urlToImage": "https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/e9d6ff047a585a5f52179c66d750fcab.jpg",
      "publishedAt": "2023-03-10T10:30:00Z",
      "content": "In early 2020, a creative agency called Space150 created an AI music bott modeled after rapped Travis Scott named, fittingly Travis Bott. The Travis Bott was trained using all of Scotts actual lyrics… [+1200 chars]"
    },
    {
      "source": {
        "id": null,
        "name": "Gizmodo.com"
      },
      "author": "Nikki Main",
      "title": "Spotify Launches 'Entirely New' Home Feed That's Very TikTok",
      "description": "Spotify is introducing a new interface comparable to a TikTok or Instagram feed, the company announced at its Stream On event on Wednesday. The change will affect how Spotify’s music is recommended to users by showing music video clips and other visual aspect…",
      "url": "https://gizmodo.com/spotify-tiktok-music-streaming-music-videos-podcast-1850204640",
      "urlToImage": "https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/b970cd1781eb1aa5248d190ae0378591.jpg",
      "publishedAt": "2023-03-08T21:23:00Z",
      "content": "Spotify is introducing a new interface comparable to a TikTok or Instagram feed, the company announced at its Stream On event on Wednesday. The change will affect how Spotifys music is recommended to… [+2602 chars]"
    }
  ]
  render() {
    return (
      <div>
        <div className="container text-center my-3">
          <div className="row">
            {this.articles.map((article) => {
              return <div className="col-md-4" key={article.url}>
                <NewsItem title={article.title.slice(0,45) + '...'} imageUrl = {article.urlToImage} description={article.description.slice(0,88) + '...'} url={article.url} />
              </div>
              }
            )
            }
          </div>
        </div>
      </div>
    )
  }
}

export default NewsComponent
